# -*- coding: utf-8 -*-
"""Edit 043s.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVFVMMV1dtWWUxdA3K2QiffFxrF9Oush
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive/')

!ls

pip install pymarc

import requests
import yaml
import csv
from oauthlib.oauth2 import BackendApplicationClient
from requests.auth import HTTPBasicAuth
from requests_oauthlib import OAuth2Session
from pymarc import MARCReader, MARCWriter, Field, Subfield

with open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/metadata2_config.yml", 'r') as stream:
    config = yaml.safe_load(stream)

serviceURL = config.get('metadata_service_url')

scope = ['WorldCatMetadataAPI:manage_bibs']

auth = HTTPBasicAuth(config.get('key'), config.get('secret'))
client = BackendApplicationClient(client_id=config.get('key'), scope=scope)
wskey = OAuth2Session(client=client)

token = wskey.fetch_token(token_url=config.get('token_url'), auth=auth)
print(token)

def generate_043_field(marc_file, country_code):
    with open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/response.mrc", "rb") as fh:
        reader = MARCReader(fh)
        for record in reader:
            new_043_field = Field(
                tag='043',
                indicators = [' ',' '],
                subfields = [
                    Subfield(code='a', value=f"{country_code}")
                ]
            )
            record.add_ordered_field(new_043_field)

            writer = MARCWriter(open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/edited.mrc", "wb"))
            writer.write(record)
            writer.close()

# def pull_record_ocn():
#     with open("response.mrc", "rb") as fh:
#         reader = MARCReader(fh)
#         for record in reader:
#             ocn = record['001'].value()
#             return ocn

def write_chunk(control_num, response):
    with open('/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/track_response_codes.csv', 'a') as response_codes:
        writer = csv.writer(response_codes)
        writer.writerow([control_num, response])

with open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/ListSingleCodes.csv") as csv_file:
    reader = csv.DictReader(csv_file)
    for line in reader:
        ocn = line["ocn"] # "ocn" is the header of the column in the csv file
        country_code = line["country_code"] # "country_code" is the header of the column in the csv file

        print("working on:", ocn)

        # Send GET request
        try:
            r = wskey.get(serviceURL + f"/manage/bibs/{ocn}", headers={'Accept': 'application/marc'})
            r.raise_for_status()

            # Write MARC from API to mrc file on local machine
            with open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/response.mrc", "wb") as start_file:
                start_file.write(r.content)
            # Read mrc file saved on local machine
            generate_043_field("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/response.mrc", country_code= country_code)

            # Read mrc file on local machine to send put request with edited record content to API
            with open("/content/drive/My Drive/Data Services/API Batch Edits On-Boarding/043s/edited.mrc", "rb") as updated_record:
                reader2 = MARCReader(updated_record)
                for record in reader2:
                    response = wskey.put(serviceURL + f"/manage/bibs/{ocn}", data=record.as_marc(), headers={'Content-Type': 'application/marc'})
                    #Put operations typically need a 'Content-Type' header to announce the file type rather than an 'Accept' header.
                reader2.close()
            print(response) #This will return the status code of the operation, 200=success 403=forbidden, etc. you can also print(response.text) to obtain more detailed info. This can be very useful for debugging
            write_chunk(ocn, response)
        except requests.exceptions.HTTPError as err:
            print(err)
        except BaseException as err:
            print(err)